name = "UnfoldPreconditioning"
uuid = "f3c5a587-0982-455b-8d33-269fc7f8524d"
SparseArrays = "2.0.0"

[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
BSplineKit = "093aae92-e908-43d7-9660-e50ee39d5a0a"
BasicLU = "f55c55da-c227-4c78-8e30-b72a48476979"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
ILUZero = "88f59080-6952-5380-9ea5-54057fb9a43f"
IncompleteLU = "40713840-3770-5561-ab4c-a76e7d0d7895"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
KLU = "ef3ab10e-7fda-4108-b977-705223b18434"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
KrylovPreconditioners = "45d422c2-293f-44ce-8315-2cb988662dec"
LDLFactorizations = "40e66cde-538c-5869-a4ad-c39174c6795b"
LimitedLDLFactorizations = "f5a24dde-3ab7-510b-b81b-6a72c6098d3b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Preconditioners = "af69fa37-3177-5a40-98ee-561f696e4fcd"
PrettyChairmarks = "aafa11c5-44f9-44a1-b829-427e6ce1ffc2"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProfileCanvas = "efd6af41-a80b-495e-886c-e51b0c7d77a3"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RandomizedPreconditioners = "3e7891d3-c9d1-416a-9949-ebd96150e4f0"
RobustModels = "d6ea1423-9682-4bbd-952f-b1577cbf8c98"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TableIO = "8545f849-0b94-433a-9b3f-37e40367303d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unfold = "181c99d8-e21b-4ff3-b70b-c233eddec679"
UnfoldMakie = "69a5ce3b-64fb-4f22-ae69-36dd4416af2a"
UnfoldSim = "ed8ae6d2-84d3-44c6-ab46-0baf21700804"

[compat]
CairoMakie = "0.13.10"
LinearSolve = "3.7.2"
SparseArrays = "1.12.0"
StatsPlots = "0.15.8"
TableIO = "0.4.1"
